execute if score ufrn:timer_tick ufrn matches 20 run title @a actionbar 300
execute if score ufrn:timer_tick ufrn matches 40 run title @a actionbar 299
execute if score ufrn:timer_tick ufrn matches 60 run title @a actionbar 298
execute if score ufrn:timer_tick ufrn matches 80 run title @a actionbar 297
execute if score ufrn:timer_tick ufrn matches 100 run title @a actionbar 296
execute if score ufrn:timer_tick ufrn matches 120 run title @a actionbar 295
execute if score ufrn:timer_tick ufrn matches 140 run title @a actionbar 294
execute if score ufrn:timer_tick ufrn matches 160 run title @a actionbar 293
execute if score ufrn:timer_tick ufrn matches 180 run title @a actionbar 292
execute if score ufrn:timer_tick ufrn matches 200 run title @a actionbar 291
execute if score ufrn:timer_tick ufrn matches 220 run title @a actionbar 290
execute if score ufrn:timer_tick ufrn matches 220 run tellraw @a {"rawtext":[{"translate":"ufrn.walkietalkie.chat.name"},{"translate":"ufrn.chat.separator"},{"translate":"ufrn.Q0006.walkietalkie.2"}]}
execute if score ufrn:timer_tick ufrn matches 220 run function event/on_walkietalkie_speak
execute if score ufrn:timer_tick ufrn matches 240 run title @a actionbar 289
execute if score ufrn:timer_tick ufrn matches 260 run title @a actionbar 288
execute if score ufrn:timer_tick ufrn matches 280 run title @a actionbar 287
execute if score ufrn:timer_tick ufrn matches 300 run title @a actionbar 286
execute if score ufrn:timer_tick ufrn matches 320 run title @a actionbar 285
execute if score ufrn:timer_tick ufrn matches 340 run title @a actionbar 284
execute if score ufrn:timer_tick ufrn matches 360 run title @a actionbar 283
execute if score ufrn:timer_tick ufrn matches 380 run title @a actionbar 282
execute if score ufrn:timer_tick ufrn matches 400 run title @a actionbar 281
execute if score ufrn:timer_tick ufrn matches 420 run title @a actionbar 280
execute if score ufrn:timer_tick ufrn matches 440 run title @a actionbar 279
execute if score ufrn:timer_tick ufrn matches 460 run title @a actionbar 278
execute if score ufrn:timer_tick ufrn matches 480 run title @a actionbar 277
execute if score ufrn:timer_tick ufrn matches 500 run title @a actionbar 276
execute if score ufrn:timer_tick ufrn matches 520 run title @a actionbar 275
execute if score ufrn:timer_tick ufrn matches 540 run title @a actionbar 274
execute if score ufrn:timer_tick ufrn matches 560 run title @a actionbar 273
execute if score ufrn:timer_tick ufrn matches 580 run title @a actionbar 272
execute if score ufrn:timer_tick ufrn matches 600 run title @a actionbar 271
execute if score ufrn:timer_tick ufrn matches 620 run title @a actionbar 270
execute if score ufrn:timer_tick ufrn matches 640 run title @a actionbar 269
execute if score ufrn:timer_tick ufrn matches 660 run title @a actionbar 268
execute if score ufrn:timer_tick ufrn matches 680 run title @a actionbar 267
execute if score ufrn:timer_tick ufrn matches 700 run title @a actionbar 266
execute if score ufrn:timer_tick ufrn matches 720 run title @a actionbar 265
execute if score ufrn:timer_tick ufrn matches 740 run title @a actionbar 264
execute if score ufrn:timer_tick ufrn matches 760 run title @a actionbar 263
execute if score ufrn:timer_tick ufrn matches 780 run title @a actionbar 262
execute if score ufrn:timer_tick ufrn matches 800 run title @a actionbar 261
execute if score ufrn:timer_tick ufrn matches 820 run title @a actionbar 260
execute if score ufrn:timer_tick ufrn matches 820 run tellraw @a {"rawtext":[{"translate":"ufrn.walkietalkie.chat.name"},{"translate":"ufrn.chat.separator"},{"translate":"ufrn.Q0006.walkietalkie.3"}]}
execute if score ufrn:timer_tick ufrn matches 820 run function event/on_walkietalkie_speak
execute if score ufrn:timer_tick ufrn matches 840 run title @a actionbar 259
execute if score ufrn:timer_tick ufrn matches 860 run title @a actionbar 258
execute if score ufrn:timer_tick ufrn matches 880 run title @a actionbar 257
execute if score ufrn:timer_tick ufrn matches 900 run title @a actionbar 256
execute if score ufrn:timer_tick ufrn matches 920 run title @a actionbar 255
execute if score ufrn:timer_tick ufrn matches 940 run title @a actionbar 254
execute if score ufrn:timer_tick ufrn matches 960 run title @a actionbar 253
execute if score ufrn:timer_tick ufrn matches 980 run title @a actionbar 252
execute if score ufrn:timer_tick ufrn matches 1000 run title @a actionbar 251
execute if score ufrn:timer_tick ufrn matches 1020 run title @a actionbar 250
execute if score ufrn:timer_tick ufrn matches 1040 run title @a actionbar 249
execute if score ufrn:timer_tick ufrn matches 1060 run title @a actionbar 248
execute if score ufrn:timer_tick ufrn matches 1080 run title @a actionbar 247
execute if score ufrn:timer_tick ufrn matches 1100 run title @a actionbar 246
execute if score ufrn:timer_tick ufrn matches 1120 run title @a actionbar 245
execute if score ufrn:timer_tick ufrn matches 1120 run tellraw @a {"rawtext":[{"translate":"ufrn.walkietalkie.chat.name"},{"translate":"ufrn.chat.separator"},{"translate":"ufrn.Q0006.walkietalkie.4"}]}
execute if score ufrn:timer_tick ufrn matches 1120 run function event/on_walkietalkie_speak
execute if score ufrn:timer_tick ufrn matches 1140 run title @a actionbar 244
execute if score ufrn:timer_tick ufrn matches 1160 run title @a actionbar 243
execute if score ufrn:timer_tick ufrn matches 1180 run title @a actionbar 242
execute if score ufrn:timer_tick ufrn matches 1200 run title @a actionbar 241
execute if score ufrn:timer_tick ufrn matches 1220 run title @a actionbar 240
execute if score ufrn:timer_tick ufrn matches 1240 run title @a actionbar 239
execute if score ufrn:timer_tick ufrn matches 1260 run title @a actionbar 238
execute if score ufrn:timer_tick ufrn matches 1280 run title @a actionbar 237
execute if score ufrn:timer_tick ufrn matches 1300 run title @a actionbar 236
execute if score ufrn:timer_tick ufrn matches 1320 run title @a actionbar 235
execute if score ufrn:timer_tick ufrn matches 1340 run title @a actionbar 234
execute if score ufrn:timer_tick ufrn matches 1360 run title @a actionbar 233
execute if score ufrn:timer_tick ufrn matches 1380 run title @a actionbar 232
execute if score ufrn:timer_tick ufrn matches 1400 run title @a actionbar 231
execute if score ufrn:timer_tick ufrn matches 1420 run title @a actionbar 230
execute if score ufrn:timer_tick ufrn matches 1440 run title @a actionbar 229
execute if score ufrn:timer_tick ufrn matches 1460 run title @a actionbar 228
execute if score ufrn:timer_tick ufrn matches 1480 run title @a actionbar 227
execute if score ufrn:timer_tick ufrn matches 1500 run title @a actionbar 226
execute if score ufrn:timer_tick ufrn matches 1520 run title @a actionbar 225
execute if score ufrn:timer_tick ufrn matches 1540 run title @a actionbar 224
execute if score ufrn:timer_tick ufrn matches 1560 run title @a actionbar 223
execute if score ufrn:timer_tick ufrn matches 1580 run title @a actionbar 222
execute if score ufrn:timer_tick ufrn matches 1600 run title @a actionbar 221
execute if score ufrn:timer_tick ufrn matches 1620 run title @a actionbar 220
execute if score ufrn:timer_tick ufrn matches 1640 run title @a actionbar 219
execute if score ufrn:timer_tick ufrn matches 1660 run title @a actionbar 218
execute if score ufrn:timer_tick ufrn matches 1680 run title @a actionbar 217
execute if score ufrn:timer_tick ufrn matches 1700 run title @a actionbar 216
execute if score ufrn:timer_tick ufrn matches 1720 run title @a actionbar 215
execute if score ufrn:timer_tick ufrn matches 1740 run title @a actionbar 214
execute if score ufrn:timer_tick ufrn matches 1760 run title @a actionbar 213
execute if score ufrn:timer_tick ufrn matches 1780 run title @a actionbar 212
execute if score ufrn:timer_tick ufrn matches 1800 run title @a actionbar 211
execute if score ufrn:timer_tick ufrn matches 1820 run title @a actionbar 210
execute if score ufrn:timer_tick ufrn matches 1840 run title @a actionbar 209
execute if score ufrn:timer_tick ufrn matches 1860 run title @a actionbar 208
execute if score ufrn:timer_tick ufrn matches 1880 run title @a actionbar 207
execute if score ufrn:timer_tick ufrn matches 1900 run title @a actionbar 206
execute if score ufrn:timer_tick ufrn matches 1920 run title @a actionbar 205
execute if score ufrn:timer_tick ufrn matches 1940 run title @a actionbar 204
execute if score ufrn:timer_tick ufrn matches 1960 run title @a actionbar 203
execute if score ufrn:timer_tick ufrn matches 1980 run title @a actionbar 202
execute if score ufrn:timer_tick ufrn matches 2000 run title @a actionbar 201
execute if score ufrn:timer_tick ufrn matches 2020 run title @a actionbar 200
execute if score ufrn:timer_tick ufrn matches 2020 run tellraw @a {"rawtext":[{"translate":"ufrn.walkietalkie.chat.name"},{"translate":"ufrn.chat.separator"},{"translate":"ufrn.Q0006.walkietalkie.5"}]}
execute if score ufrn:timer_tick ufrn matches 2020 run function event/on_walkietalkie_speak
execute if score ufrn:timer_tick ufrn matches 2040 run title @a actionbar 199
execute if score ufrn:timer_tick ufrn matches 2060 run title @a actionbar 198
execute if score ufrn:timer_tick ufrn matches 2080 run title @a actionbar 197
execute if score ufrn:timer_tick ufrn matches 2100 run title @a actionbar 196
execute if score ufrn:timer_tick ufrn matches 2120 run title @a actionbar 195
execute if score ufrn:timer_tick ufrn matches 2140 run title @a actionbar 194
execute if score ufrn:timer_tick ufrn matches 2160 run title @a actionbar 193
execute if score ufrn:timer_tick ufrn matches 2180 run title @a actionbar 192
execute if score ufrn:timer_tick ufrn matches 2200 run title @a actionbar 191
execute if score ufrn:timer_tick ufrn matches 2220 run title @a actionbar 190
execute if score ufrn:timer_tick ufrn matches 2240 run title @a actionbar 189
execute if score ufrn:timer_tick ufrn matches 2260 run title @a actionbar 188
execute if score ufrn:timer_tick ufrn matches 2280 run title @a actionbar 187
execute if score ufrn:timer_tick ufrn matches 2300 run title @a actionbar 186
execute if score ufrn:timer_tick ufrn matches 2320 run title @a actionbar 185
execute if score ufrn:timer_tick ufrn matches 2340 run title @a actionbar 184
execute if score ufrn:timer_tick ufrn matches 2360 run title @a actionbar 183
execute if score ufrn:timer_tick ufrn matches 2380 run title @a actionbar 182
execute if score ufrn:timer_tick ufrn matches 2400 run title @a actionbar 181
execute if score ufrn:timer_tick ufrn matches 2420 run title @a actionbar 180
execute if score ufrn:timer_tick ufrn matches 2440 run title @a actionbar 179
execute if score ufrn:timer_tick ufrn matches 2460 run title @a actionbar 178
execute if score ufrn:timer_tick ufrn matches 2480 run title @a actionbar 177
execute if score ufrn:timer_tick ufrn matches 2500 run title @a actionbar 176
execute if score ufrn:timer_tick ufrn matches 2520 run title @a actionbar 175
execute if score ufrn:timer_tick ufrn matches 2540 run title @a actionbar 174
execute if score ufrn:timer_tick ufrn matches 2560 run title @a actionbar 173
execute if score ufrn:timer_tick ufrn matches 2580 run title @a actionbar 172
execute if score ufrn:timer_tick ufrn matches 2600 run title @a actionbar 171
execute if score ufrn:timer_tick ufrn matches 2620 run title @a actionbar 170
execute if score ufrn:timer_tick ufrn matches 2640 run title @a actionbar 169
execute if score ufrn:timer_tick ufrn matches 2660 run title @a actionbar 168
execute if score ufrn:timer_tick ufrn matches 2680 run title @a actionbar 167
execute if score ufrn:timer_tick ufrn matches 2700 run title @a actionbar 166
execute if score ufrn:timer_tick ufrn matches 2720 run title @a actionbar 165
execute if score ufrn:timer_tick ufrn matches 2740 run title @a actionbar 164
execute if score ufrn:timer_tick ufrn matches 2760 run title @a actionbar 163
execute if score ufrn:timer_tick ufrn matches 2780 run title @a actionbar 162
execute if score ufrn:timer_tick ufrn matches 2800 run title @a actionbar 161
execute if score ufrn:timer_tick ufrn matches 2820 run title @a actionbar 160
execute if score ufrn:timer_tick ufrn matches 2840 run title @a actionbar 159
execute if score ufrn:timer_tick ufrn matches 2860 run title @a actionbar 158
execute if score ufrn:timer_tick ufrn matches 2880 run title @a actionbar 157
execute if score ufrn:timer_tick ufrn matches 2900 run title @a actionbar 156
execute if score ufrn:timer_tick ufrn matches 2920 run title @a actionbar 155
execute if score ufrn:timer_tick ufrn matches 2940 run title @a actionbar 154
execute if score ufrn:timer_tick ufrn matches 2960 run title @a actionbar 153
execute if score ufrn:timer_tick ufrn matches 2980 run title @a actionbar 152
execute if score ufrn:timer_tick ufrn matches 3000 run title @a actionbar 151
execute if score ufrn:timer_tick ufrn matches 3020 run title @a actionbar 150
execute if score ufrn:timer_tick ufrn matches 3040 run title @a actionbar 149
execute if score ufrn:timer_tick ufrn matches 3060 run title @a actionbar 148
execute if score ufrn:timer_tick ufrn matches 3080 run title @a actionbar 147
execute if score ufrn:timer_tick ufrn matches 3100 run title @a actionbar 146
execute if score ufrn:timer_tick ufrn matches 3120 run title @a actionbar 145
execute if score ufrn:timer_tick ufrn matches 3140 run title @a actionbar 144
execute if score ufrn:timer_tick ufrn matches 3160 run title @a actionbar 143
execute if score ufrn:timer_tick ufrn matches 3180 run title @a actionbar 142
execute if score ufrn:timer_tick ufrn matches 3200 run title @a actionbar 141
execute if score ufrn:timer_tick ufrn matches 3220 run title @a actionbar 140
execute if score ufrn:timer_tick ufrn matches 3240 run title @a actionbar 139
execute if score ufrn:timer_tick ufrn matches 3260 run title @a actionbar 138
execute if score ufrn:timer_tick ufrn matches 3280 run title @a actionbar 137
execute if score ufrn:timer_tick ufrn matches 3300 run title @a actionbar 136
execute if score ufrn:timer_tick ufrn matches 3320 run title @a actionbar 135
execute if score ufrn:timer_tick ufrn matches 3340 run title @a actionbar 134
execute if score ufrn:timer_tick ufrn matches 3360 run title @a actionbar 133
execute if score ufrn:timer_tick ufrn matches 3380 run title @a actionbar 132
execute if score ufrn:timer_tick ufrn matches 3400 run title @a actionbar 131
execute if score ufrn:timer_tick ufrn matches 3420 run title @a actionbar 130
execute if score ufrn:timer_tick ufrn matches 3440 run title @a actionbar 129
execute if score ufrn:timer_tick ufrn matches 3460 run title @a actionbar 128
execute if score ufrn:timer_tick ufrn matches 3480 run title @a actionbar 127
execute if score ufrn:timer_tick ufrn matches 3500 run title @a actionbar 126
execute if score ufrn:timer_tick ufrn matches 3520 run title @a actionbar 125
execute if score ufrn:timer_tick ufrn matches 3540 run title @a actionbar 124
execute if score ufrn:timer_tick ufrn matches 3560 run title @a actionbar 123
execute if score ufrn:timer_tick ufrn matches 3580 run title @a actionbar 122
execute if score ufrn:timer_tick ufrn matches 3600 run title @a actionbar 121
execute if score ufrn:timer_tick ufrn matches 3620 run title @a actionbar 120
execute if score ufrn:timer_tick ufrn matches 3640 run title @a actionbar 119
execute if score ufrn:timer_tick ufrn matches 3660 run title @a actionbar 118
execute if score ufrn:timer_tick ufrn matches 3680 run title @a actionbar 117
execute if score ufrn:timer_tick ufrn matches 3700 run title @a actionbar 116
execute if score ufrn:timer_tick ufrn matches 3720 run title @a actionbar 115
execute if score ufrn:timer_tick ufrn matches 3740 run title @a actionbar 114
execute if score ufrn:timer_tick ufrn matches 3760 run title @a actionbar 113
execute if score ufrn:timer_tick ufrn matches 3780 run title @a actionbar 112
execute if score ufrn:timer_tick ufrn matches 3800 run title @a actionbar 111
execute if score ufrn:timer_tick ufrn matches 3820 run title @a actionbar 110
execute if score ufrn:timer_tick ufrn matches 3840 run title @a actionbar 109
execute if score ufrn:timer_tick ufrn matches 3860 run title @a actionbar 108
execute if score ufrn:timer_tick ufrn matches 3880 run title @a actionbar 107
execute if score ufrn:timer_tick ufrn matches 3900 run title @a actionbar 106
execute if score ufrn:timer_tick ufrn matches 3920 run title @a actionbar 105
execute if score ufrn:timer_tick ufrn matches 3940 run title @a actionbar 104
execute if score ufrn:timer_tick ufrn matches 3960 run title @a actionbar 103
execute if score ufrn:timer_tick ufrn matches 3980 run title @a actionbar 102
execute if score ufrn:timer_tick ufrn matches 4000 run title @a actionbar 101
execute if score ufrn:timer_tick ufrn matches 4020 run title @a actionbar 100
execute if score ufrn:timer_tick ufrn matches 4020 run tellraw @a {"rawtext":[{"translate":"ufrn.walkietalkie.chat.name"},{"translate":"ufrn.chat.separator"},{"translate":"ufrn.Q0006.walkietalkie.6"}]}
execute if score ufrn:timer_tick ufrn matches 4020 run function event/on_walkietalkie_speak
execute if score ufrn:timer_tick ufrn matches 4040 run title @a actionbar 99
execute if score ufrn:timer_tick ufrn matches 4060 run title @a actionbar 98
execute if score ufrn:timer_tick ufrn matches 4080 run title @a actionbar 97
execute if score ufrn:timer_tick ufrn matches 4100 run title @a actionbar 96
execute if score ufrn:timer_tick ufrn matches 4120 run title @a actionbar 95
execute if score ufrn:timer_tick ufrn matches 4140 run title @a actionbar 94
execute if score ufrn:timer_tick ufrn matches 4160 run title @a actionbar 93
execute if score ufrn:timer_tick ufrn matches 4180 run title @a actionbar 92
execute if score ufrn:timer_tick ufrn matches 4200 run title @a actionbar 91
execute if score ufrn:timer_tick ufrn matches 4220 run title @a actionbar 90
execute if score ufrn:timer_tick ufrn matches 4240 run title @a actionbar 89
execute if score ufrn:timer_tick ufrn matches 4260 run title @a actionbar 88
execute if score ufrn:timer_tick ufrn matches 4280 run title @a actionbar 87
execute if score ufrn:timer_tick ufrn matches 4300 run title @a actionbar 86
execute if score ufrn:timer_tick ufrn matches 4320 run title @a actionbar 85
execute if score ufrn:timer_tick ufrn matches 4340 run title @a actionbar 84
execute if score ufrn:timer_tick ufrn matches 4360 run title @a actionbar 83
execute if score ufrn:timer_tick ufrn matches 4380 run title @a actionbar 82
execute if score ufrn:timer_tick ufrn matches 4400 run title @a actionbar 81
execute if score ufrn:timer_tick ufrn matches 4420 run title @a actionbar 80
execute if score ufrn:timer_tick ufrn matches 4440 run title @a actionbar 79
execute if score ufrn:timer_tick ufrn matches 4460 run title @a actionbar 78
execute if score ufrn:timer_tick ufrn matches 4480 run title @a actionbar 77
execute if score ufrn:timer_tick ufrn matches 4500 run title @a actionbar 76
execute if score ufrn:timer_tick ufrn matches 4520 run title @a actionbar 75
execute if score ufrn:timer_tick ufrn matches 4540 run title @a actionbar 74
execute if score ufrn:timer_tick ufrn matches 4560 run title @a actionbar 73
execute if score ufrn:timer_tick ufrn matches 4580 run title @a actionbar 72
execute if score ufrn:timer_tick ufrn matches 4600 run title @a actionbar 71
execute if score ufrn:timer_tick ufrn matches 4620 run title @a actionbar 70
execute if score ufrn:timer_tick ufrn matches 4640 run title @a actionbar 69
execute if score ufrn:timer_tick ufrn matches 4660 run title @a actionbar 68
execute if score ufrn:timer_tick ufrn matches 4680 run title @a actionbar 67
execute if score ufrn:timer_tick ufrn matches 4700 run title @a actionbar 66
execute if score ufrn:timer_tick ufrn matches 4720 run title @a actionbar 65
execute if score ufrn:timer_tick ufrn matches 4740 run title @a actionbar 64
execute if score ufrn:timer_tick ufrn matches 4760 run title @a actionbar 63
execute if score ufrn:timer_tick ufrn matches 4780 run title @a actionbar 62
execute if score ufrn:timer_tick ufrn matches 4800 run title @a actionbar 61
execute if score ufrn:timer_tick ufrn matches 4820 run title @a actionbar 60
execute if score ufrn:timer_tick ufrn matches 4840 run title @a actionbar 59
execute if score ufrn:timer_tick ufrn matches 4860 run title @a actionbar 58
execute if score ufrn:timer_tick ufrn matches 4880 run title @a actionbar 57
execute if score ufrn:timer_tick ufrn matches 4900 run title @a actionbar 56
execute if score ufrn:timer_tick ufrn matches 4920 run title @a actionbar 55
execute if score ufrn:timer_tick ufrn matches 4940 run title @a actionbar 54
execute if score ufrn:timer_tick ufrn matches 4960 run title @a actionbar 53
execute if score ufrn:timer_tick ufrn matches 4980 run title @a actionbar 52
execute if score ufrn:timer_tick ufrn matches 5000 run title @a actionbar 51
execute if score ufrn:timer_tick ufrn matches 5020 run title @a actionbar 50
execute if score ufrn:timer_tick ufrn matches 5040 run title @a actionbar 49
execute if score ufrn:timer_tick ufrn matches 5060 run title @a actionbar 48
execute if score ufrn:timer_tick ufrn matches 5080 run title @a actionbar 47
execute if score ufrn:timer_tick ufrn matches 5100 run title @a actionbar 46
execute if score ufrn:timer_tick ufrn matches 5120 run title @a actionbar 45
execute if score ufrn:timer_tick ufrn matches 5140 run title @a actionbar 44
execute if score ufrn:timer_tick ufrn matches 5160 run title @a actionbar 43
execute if score ufrn:timer_tick ufrn matches 5180 run title @a actionbar 42
execute if score ufrn:timer_tick ufrn matches 5200 run title @a actionbar 41
execute if score ufrn:timer_tick ufrn matches 5220 run title @a actionbar 40
execute if score ufrn:timer_tick ufrn matches 5240 run title @a actionbar 39
execute if score ufrn:timer_tick ufrn matches 5260 run title @a actionbar 38
execute if score ufrn:timer_tick ufrn matches 5280 run title @a actionbar 37
execute if score ufrn:timer_tick ufrn matches 5300 run title @a actionbar 36
execute if score ufrn:timer_tick ufrn matches 5320 run title @a actionbar 35
execute if score ufrn:timer_tick ufrn matches 5340 run title @a actionbar 34
execute if score ufrn:timer_tick ufrn matches 5360 run title @a actionbar 33
execute if score ufrn:timer_tick ufrn matches 5380 run title @a actionbar 32
execute if score ufrn:timer_tick ufrn matches 5400 run title @a actionbar 31
execute if score ufrn:timer_tick ufrn matches 5420 run title @a actionbar 30
execute if score ufrn:timer_tick ufrn matches 5440 run title @a actionbar 29
execute if score ufrn:timer_tick ufrn matches 5460 run title @a actionbar 28
execute if score ufrn:timer_tick ufrn matches 5480 run title @a actionbar 27
execute if score ufrn:timer_tick ufrn matches 5500 run title @a actionbar 26
execute if score ufrn:timer_tick ufrn matches 5520 run title @a actionbar 25
execute if score ufrn:timer_tick ufrn matches 5540 run title @a actionbar 24
execute if score ufrn:timer_tick ufrn matches 5560 run title @a actionbar 23
execute if score ufrn:timer_tick ufrn matches 5580 run title @a actionbar 22
execute if score ufrn:timer_tick ufrn matches 5600 run title @a actionbar 21
execute if score ufrn:timer_tick ufrn matches 5620 run title @a actionbar 20
execute if score ufrn:timer_tick ufrn matches 5640 run title @a actionbar 19
execute if score ufrn:timer_tick ufrn matches 5660 run title @a actionbar 18
execute if score ufrn:timer_tick ufrn matches 5680 run title @a actionbar 17
execute if score ufrn:timer_tick ufrn matches 5700 run title @a actionbar 16
execute if score ufrn:timer_tick ufrn matches 5720 run title @a actionbar 15
execute if score ufrn:timer_tick ufrn matches 5740 run title @a actionbar 14
execute if score ufrn:timer_tick ufrn matches 5760 run title @a actionbar 13
execute if score ufrn:timer_tick ufrn matches 5780 run title @a actionbar 12
execute if score ufrn:timer_tick ufrn matches 5800 run title @a actionbar 11
execute if score ufrn:timer_tick ufrn matches 5820 run title @a actionbar 10
execute if score ufrn:timer_tick ufrn matches 5840 run title @a actionbar 9
execute if score ufrn:timer_tick ufrn matches 5860 run title @a actionbar 8
execute if score ufrn:timer_tick ufrn matches 5880 run title @a actionbar 7
execute if score ufrn:timer_tick ufrn matches 5900 run title @a actionbar 6
execute if score ufrn:timer_tick ufrn matches 5920 run title @a actionbar 5
execute if score ufrn:timer_tick ufrn matches 5940 run title @a actionbar 4
execute if score ufrn:timer_tick ufrn matches 5960 run title @a actionbar 3
execute if score ufrn:timer_tick ufrn matches 5980 run title @a actionbar 2
execute if score ufrn:timer_tick ufrn matches 6000 run title @a actionbar 1
execute if score ufrn:timer_tick ufrn matches 6001 run function event/on_timer_desable

